### PR TITLE
Updating outdated dependencies and addressing vulnerabilities

### PR DESCRIPTION
**Pull request by BlackBaroness**
Hi.

I've enabled Dependabot and updated outdated dependencies for the repository, including addressing multiple vulnerabilities in old versions of gson and snakeyaml.

I noticed that some tests are failing after updating snakeyaml to the latest version, and I'm currently investigating the issue. However, I cannot promise that I can fix the issue on my own. I wanted to bring this to your attention so that you're aware of the issue, and we can work together to address it.

I believe it's important for libraries to use up-to-date and secure dependencies, so I felt it was necessary to address the vulnerabilities in the outdated dependencies. If any additional changes were made, I will be sure to include them in this pull request.

Let me know if you have any questions or concerns.

Stacktrace for tests:
```
[ERROR] space.arim.dazzleconf.ext.snakeyaml.YamlWriterTest.writeComments(Factory)[2]  Time elapsed: 0.004 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected 13 lines, but only got 9
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertLinesMatch$LinesMatcher.fail(AssertLinesMatch.java:203)
        at org.junit.jupiter.api.AssertLinesMatch$LinesMatcher.assertLinesMatch(AssertLinesMatch.java:101)
        at org.junit.jupiter.api.AssertLinesMatch.assertLinesMatch(AssertLinesMatch.java:80)
        at org.junit.jupiter.api.AssertLinesMatch.assertLinesMatch(AssertLinesMatch.java:42)
        at org.junit.jupiter.api.Assertions.assertLinesMatch(Assertions.java:1600)
        at space.arim.dazzleconf.ext.snakeyaml@1.3.0-SNAPSHOT/space.arim.dazzleconf.ext.snakeyaml.YamlWriterTest.assertLinesMatch(YamlWriterTest.java:78)
        at space.arim.dazzleconf.ext.snakeyaml@1.3.0-SNAPSHOT/space.arim.dazzleconf.ext.snakeyaml.YamlWriterTest.writeComments(YamlWriterTest.java:170)
```

```
[ERROR] space.arim.dazzleconf.ext.snakeyaml.YamlWriterTest.writeCommentHeader(Factory)[2]  Time elapsed: 0.026 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected 4 lines, but only got 1
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertLinesMatch$LinesMatcher.fail(AssertLinesMatch.java:203)
        at org.junit.jupiter.api.AssertLinesMatch$LinesMatcher.assertLinesMatch(AssertLinesMatch.java:101)
        at org.junit.jupiter.api.AssertLinesMatch.assertLinesMatch(AssertLinesMatch.java:80)
        at org.junit.jupiter.api.AssertLinesMatch.assertLinesMatch(AssertLinesMatch.java:42)
        at org.junit.jupiter.api.Assertions.assertLinesMatch(Assertions.java:1600)
        at space.arim.dazzleconf.ext.snakeyaml@1.3.0-SNAPSHOT/space.arim.dazzleconf.ext.snakeyaml.YamlWriterTest.assertLinesMatch(YamlWriterTest.java:78)
        at space.arim.dazzleconf.ext.snakeyaml@1.3.0-SNAPSHOT/space.arim.dazzleconf.ext.snakeyaml.YamlWriterTest.writeCommentHeader(YamlWriterTest.java:201)
```

### CODE REVIEW

**Comment by A248** [comment]
Hi, thanks for bringing this to my attention. I can see that you have been quite thorough in updating declared dependencies. It is appreciated considering the simultaneous importance and annoyance of dependency management.

Regarding snakeyaml, have you attempted to use DazzleConf, as one would in a typical "production" environment, to see whether it functions as intended? The feature that is failing is comment support, which can be enabled using either SnakeYaml's built-in comment handling from newer versions or the "alternative writer" we implement. Perhaps there was a breaking change in SnakeYaml that broke its comment API.

So that you know -- the vulnerabilities in SnakeYaml and Gson relate to handling untrusted input. It's still very worth to fix these vulnerabilities, as well as keep dependencies up-to-date in general. It is possible someone is using DazzleConf to handle untrusted input, though I have never marketed the library that way, and I would be surprised if someone relied upon it as a general-purpose data serialization mechanism, especially considering the generalized flexibility built into this library's user-friendly deserialization.

**Comment by BlackBaroness** [comment]
> So that you know -- the vulnerabilities in SnakeYaml and Gson relate to handling untrusted input.

Yes, I know, vulnerabilities are not so important in this situation, but it is probably better to get rid of them.

> Regarding snakeyaml, have you attempted to use DazzleConf, as one would in a typical "production" environment, to see whether it functions as intended?

No, because I saw failing tests and I decided to deal with them first. I can test the library by skipping the tests if you want. I'm currently writing a project using DazzleConf and it won't be hard for me to test.

**Comment by A248** [comment]
Thanks for raising this once again. I have included most of your changes in the latest commit to master, namely the version updates. The next release of DazzleConf will therefore use the updated dependency versions from this PR.

Regarding SnakeYaml, I took a full dive into their mess of versions and breaking changes. Because they don't follow semantic versioning, the comment support added in version 1.28 must be enabled via a new method in 1.29+. Moreover, version 2.0, since released, has still further breaking changes. To accomodate all of this, DazzleConf will enable comments if possible and avoid calling APIs that change between 1.15 and 2.0, the range of versions we support. There are accompanying integration tests.

Dependabot, however, I politely decline to add to this repository, my reason being that the tool has caused me plenty of headache yet no real benefit. As matters stand, I receive notifications of CVEs from Github even when Dependabot is disabled, and update dependencies when the situation demands. Most commonly, I read about untrusted input in serialization and networking libraries my software uses; however, most of these are practically irrelevant. When Dependabot is enabled, and when I have enabled it in the past on my repositories, the result is a slew of PRs that are annoying and energy-draining. You are welcome to try and persuade me otherwise, but I suspect it is highly unlikely I'll be approving Dependabot into DazzleConf's repository.

All the same I have included and squashed your other commits into my latest commit, and I'll credit you in the next release.

**Comment by BlackBaroness** [comment]
> Most commonly, I read about untrusted input in serialization and networking libraries my software uses; however, most of these are practically irrelevant. When Dependabot is enabled, and when I have enabled it in the past on my repositories, the result is a slew of PRs that are annoying and energy-draining. You are welcome to try and persuade me otherwise, but I suspect it is highly unlikely I'll be approving Dependabot into DazzleConf's repository.

Thanks for your work. Besides, I don't really like Dependabot, I usually use Renovate which even have "all updates at single PR" feature.

**Pull request closed without merging**
